on:
  push:
    branches:
      - production
      - beta
      - alpha
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'

      - name: Decode android/app/keystore.jks
        run: echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > android/app/keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - run: flutter pub get
      - run: flutter build appbundle --build-number=${{ github.run_number }} --build-name=2022.02.${{ github.run_number }} --obfuscate --split-debug-info=./build/app/outputs/symbols

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.kateile.stg
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: ${{ github.ref_name }}
          inAppUpdatePriority: 2
          whatsNewDirectory: whatsnew
          #mappingFile: build/app/outputs/symbols/mapping.txt